### PR TITLE
Revert the name of the execution script to OUT_FILE_INPUT_SCRIPT

### PR DESCRIPTION
**Pull request by hothello**
When a user specifies a custom LT name to create the input deck for LAMMPS, the execution script should also inherit the same root, as it was up to the 24 Jun 22. This is a very trivial change. I hope it is in line with the intended use of Moltemplate.
Cheers!

### CODE REVIEW

**Comment by hothello** [comment]
I have added the option -run-example to make it optional to append the example Run Section at the end of the LAMMPS input script. I have also changed the cp -p and cat commands to a sed regexp removing leading spaces, which improve the readability of LT files but are annoying in the rendered input deck.

**Comment by hothello** [comment]
We should say to the ATB team that a new option -overlay-all is available. This change goes in the direction of streamlining Moltemplate usage.

**Comment by jewettaij** [comment]
Thank you for your patience and all of your thoughtful changes that you made in this diff, Otello.  There were a lot of improvements (even to the manual!).

I will compile the new manual and upload it to moltemplate.org today.

These days, I have to do work on moltemplate when my family is asleep.  I just have been too sleep deprived myself to face it.  Hopefully that will change.  I have not abandoned moltemplate!

**Comment by jewettaij** [comment]
I will also get the new version of moltemplate (v2.20.18) uploaded to https://moltemplate.org/download today.

Thank you very much, again!

**Pull request merged**
