### PR TITLE
Here it is

### PR DESCRIPTION
**Pull request by hothello**
Bugfix in SplitQuotedString. No idea if this is going to break other parts of the code!

### CODE REVIEW

**Comment by jewettaij** [comment]
Hi Otello.  Oh dear.  It looks like we were working on the same bug simultaneously.  I just posted my bug fix 5 minutes ago.
   You are right that the source of the bug was changes in the "SplitQuotedString()" function in the "ttree_lex.py" file.  I don't know if the changes you made in this pull request fix the problem with your molc example.  But the changes I made in my last two commits also fix the problem.  (And I can understand my changes more easily than yours, so I prefer to use mine.)
  Please try downloading the latest version of moltemplate, try it on different examples, and let me know if I fixed the problem.  If so, I'll probably close this pull request without merging.  I hope that's okay.
   Thanks for your hard work reporting and fixing bugs in moltemplate!
-Andrew

**Comment by hothello** [comment]
Thanks, this solves the problem. Please close this pull request, as my changes may have unintended consequences in other parts of the code.

**Comment by hothello** [comment]
I mean, I have tested the latest version with more convoluted examples and it works as intended. Cheers!

**Comment by jewettaij** [comment]
That's great.
And feel free to send more examples my way.  (They make good test cases.)

**Pull request closed without merging**
