### PR TITLE
Bugfix: read dump now handles ellipsoid orientation correctly

### PR DESCRIPTION
**Pull request by hothello**
Hi Andrew, just a quick fix to read the quaternion information in the DUMP files. Ignore all the spurious changes in the example directory. Cheers!

### CODE REVIEW

**Comment by jewettaij** [comment]
Hi Otello
   Please forgive me for taking so long to get back to you.  I have never taken so long to reply to a bug fix.  Sometimes life gets in the way.  It seems likely that my future does not involve molecular dynamics, but I am committed to maintaining moltemplate!
   I don't understand why, but github thinks that one of your commits (1ddcd56) has 74484 changes in 424 different files.).  So I declined to accept your pull request because I am afraid it will increase the size of the moltemplate download to have all of those changes.  Instead, I downloaded your new "moltemplate.sh" file from your latest commit (0dd63e1), and it looks like you only made 2 changes:

```
687c687
<         quat=( $(sed -n '9p;9q' "$tmp_dump" | awk '{for(i=1; i<=NF; i++){if($i~/q[wxyz]/||$i~/c_q/||$i~/c_orient/){printf "%i\n",i-2} }}') )
---
>         quat=( $(sed -n '9p;9q' "$tmp_dump" | awk '{for(i=1; i<=NF; i++){if($i~/q[wxyz]/){printf "%i\n",i-2} }}') )
2255c2255
<     export MOLTEMPLATE_CITE_LIST=`printf "$MOLTEMPLATE_CITE_LIST\nRicci et al. Phys.Chem.Chem.Phys 2019 (https://doi.org/10.1039/c9cp04120f)\n"`
---
>     export MOLTEMPLATE_CITE_LIST=`printf "$MOLTEMPLATE_CITE_LIST\nRicci et al. Phys.Chem.Chem.Phys 2021 (https://doi.org/10.1039/c9cp04120f)\n"`
2429c2429
<     
---
> 
```

I made these changes in my copy of "moltemplate.sh" and committed the changes (commit [a9dfb8c](https://github.com/jewettaij/moltemplate/commit/a9dfb8c55cb4bc6a3561f6667ebed532a70a345c)).
If you have time, please download the latest version of moltemplate and let me know if it works correctly.

Thanks for  mmaintainingt hte ellipsoid code.  And thanks for fixing the date on the publication.  (It's not a cosmetic change.  I want people to cite it correctly!)
Sorry again for the long delay.

-Andrew

**Comment by jewettaij** [comment]
I'm closing the PR request because I think the latest commit probably has the changes you want.
Feel free to reopen it if the code is still not working or if I left something out.  (Or send a new PR with just those changes.)
Cheers.

Andrew

**Comment by hothello** [comment]
Hi Andrew, thanks for fixing this issue. The problem with the bogus changes originated on my local copy of moltemplate. Now I need to clean my local branch before making new changes. However, at the moment, the code works as expected. Cheers!

**Comment by jewettaij** [comment]
Thanks Otello for getting back to me about this.  I'm glad it works now.

**Pull request closed without merging**
