### PR TITLE
Dump read capability + bugfix.

### PR DESCRIPTION
**Pull request by hothello**
1. The original Internal Field Separator is saved to $OIFS once and for all at the beginning of moltemplate.sh. The newline is defined as $CR, so that IFS can be set to $CR or $OIFS anywhere in the script.

2. In option -xyz, changed "NF==4" to "(NF>3) && (NR>2)" in order to be more tolerant with non-standard formats such as XYZQ.

3. in -pdb, I have fixed the formulas for the triclinic box: now it works again. Fixed typos in BOXSIZE_Y, BOXSIZE_XZ; cosmetic change in BOXSIZE_YZ and reverted to the wikipedia-style definition of BOXSIZE_Z, which yields smaller rounding errors.

4. Added the brand-new -dump option to read DUMP files, extracting: atomic coordinates, ellipsoid quaternions, and velocities. I have also changed the corresponding ellipsoid section in $OUT_DATA_FILE.

5. Added "Ellipsoids" to the list of sections in dump2data.py

### CODE REVIEW

**Comment by jewettaij** [comment]
These changes look fantastic!  I won't have time to test this until the paper goes out, but right after that, it will be my top priority.

(As mentioned in my email reply, please send me a version of the LAMMPS code for MOLC that works with your biphenyl example.)

**Comment by hothello** [comment]
Hi Andrew. I have changed the dump option yet again. Now it is more general and should work also with other atom styles. Since quaternions are not included in the "dump custom" command, the only caveat is that they must be dumped after the atomic coordinates. I have checked that orthorhombic and triclinic boxes are written correctly, for both "-pdb" and "-dump" options. Try to open a DUMP/DATA file with VMD and convert it to PDB and compare the resulting crystal cells.

**Comment by jewettaij** [comment]
> P/DATA file with VMD and convert it to PDB and compare the resulting crystal cells.

Hi Otello
   I have not explored your patch in detail yet, but I did try the new "dump2data.py".  It no longer crashes now when the data file has an "Ellipsoids" section.  Thanks!
   I wanted to let you know I have found additional problems with "dump2data.py" (which are not your fault), and that I have decided to work on fixing them.  (Perhaps you don't need this feature, but it is bothering me, so I want to fix it.)  I just wanted to warn you about this, in case you are also working on "dump2data.py".  I want to avoid duplicating each other's efforts.
   
## Details: more dump2data.py bugs (feel free to skip)
I spent a few hours trying to get dump2data.py to work on the trajectories from your biphenyl example.  While it understands the "Ellipsoids" section in the data file, it does not correctly understand the quaternions in the dump file.  (Again, this is not your fault.)  I edited the "dump2data.py" file and fixed an obvious bug .  Now dump2data.py can run on your dump files without crashing.  However I doubt even after this patch I'm pretty sure it is not behaving correctly.  (It seems to ignore the "quatw" component of the quaternion, mistakenly interpreting the quaternion as a 3-D vector.  I think this is because the code was copied from a different program which has since been rewritten.)  To be honest, this code (and the ltemplify.py code) is some of the most ghastly code I have ever written.  I salute you in your bravery  (And I feel sorry to you for any pain this may have caused you.)  I think the solution to this problem is for me to rewrite the part of this code which interprets dipoles and quaternions (getting rid of those cryptic "ii_vects" variables).  Anyway, I just wanted to let you know I am aware of the additional bugs in "dump2data.py" and am slowly working on them.  I'll take a look at the other changes in your pull request soon also.

If for some reason, you want me to send you the version of "dump2data.py" that I have, I can do that.  (But I don't recommend it, since the approach probably does not work.)

Cheers
Andrew

**Comment by hothello** [comment]
Hi Andrew,

The problem with the quaternions is that they are not readily available in
the dump file, for instance through the "custom" option.
As such, there is no way to extract their position from the labels. This is
the ugly part in my code.

To fix the issue, one should purpose to modify the dump command in lammps
and add the quaternions to the list of available observables, naming them
something like "qw qi qj qk".

Thanks for getting back to me.

Otello

**Comment by jewettaij** [comment]
Awesome.
Thanks for contributing this Otello!

**Comment by hothello** [comment]
Thanks for accepting my pull request. I am so happy to be part of your project :)

**Pull request merged**
